# Generated by Django 2.1.5 on 2019-02-17 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestions',
            old_name='suggestions_text',
            new_name='text',
        ),
        migrations.AddField(
            model_name='suggestions',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='suggestions',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
